import type { VocabWord } from '../types'

type MemoryHook = NonNullable<VocabWord['memoryHook']>

export const antigravityHooks: Record<string, MemoryHook> = {
  facilitate: {
    core: '让一件事更容易发生或推进。',
    image: '会议前发清晰议程，大家更快进入讨论。',
    breakdown: '常搭 communication, learning, growth；比 promote 更偏“降低阻力”。',
    cue: 'facilitate communication',
    personalPrompt: 'A tool that facilitates my study is ___.',
  },
  constrain: {
    core: '被条件限制，选择变少。',
    image: '预算太少，团队只能先做最重要的功能。',
    breakdown: '常搭 budget, time, rules, growth；不是自己不想做。',
    cue: 'constrain growth',
    personalPrompt: 'Limited ___ constrains my plan to ___.',
  },
  derive: {
    core: '从某个来源得到或源于。',
    image: '你从用户反馈里得到产品改进方向。',
    breakdown: 'derive value/benefit/meaning from；强调来源，不只是 receive。',
    cue: 'derive value from',
    personalPrompt: 'I derive value from ___ because ___.',
  },
  coherent: {
    core: '整体连贯，各部分说得通。',
    image: '报告从问题、证据到结论一路顺下来。',
    breakdown: '常形容 argument, plan, explanation；重点是一致和清楚。',
    cue: 'coherent argument',
    personalPrompt: 'A coherent explanation of ___ should include ___.',
  },
  substantial: {
    core: '数量、程度或影响很有分量。',
    image: '不是小修小补，而是速度明显快了一截。',
    breakdown: '常搭 evidence, progress, increase；比 big 更正式。',
    cue: 'substantial evidence',
    personalPrompt: 'I made substantial progress in ___ when ___.',
  },
  subsequent: {
    core: '在某事之后发生的。',
    image: '上线后，后续更新修复了登录问题。',
    breakdown: '常搭 changes, events, studies；正式表达时间顺序。',
    cue: 'subsequent changes',
    personalPrompt: 'Subsequent changes made ___ better by ___.',
  },
  allocate: {
    core: '把有限资源分配给用途。',
    image: '把两小时学习时间分给听力和复习。',
    breakdown: '常搭 time, money, resources；强调有计划地分。',
    cue: 'allocate resources',
    personalPrompt: 'I allocate ___ minutes each day to ___.',
  },
  reinforce: {
    core: '加强已有印象、规则或结构。',
    image: '今天学词，明天造句，记忆被加固。',
    breakdown: '常搭 learning, belief, rule；不是从零开始学。',
    cue: 'reinforce learning',
    personalPrompt: 'Reviewing ___ reinforces my ___.',
  },
  undergo: {
    core: '经历一个过程或变化。',
    image: '新员工先接受培训，再加入项目。',
    breakdown: '常搭 training, treatment, change；语气正式，常指被动经历。',
    cue: 'undergo training',
    personalPrompt: 'I underwent ___ before I could ___.',
  },
  attribute: {
    core: '把结果归因于某原因。',
    image: '成绩提高了，你说主要因为每天复习。',
    breakdown: '结构 attribute A to B；也可作名词“属性”。',
    cue: 'attribute success to',
    personalPrompt: 'I attribute my improvement to ___.',
  },
  encompass: {
    core: '范围涵盖多个部分。',
    image: '英语学习包括词汇、听力、阅读和输出。',
    breakdown: '比 include 更强调整体覆盖范围。',
    cue: 'encompass multiple areas',
    personalPrompt: 'My learning plan encompasses ___ and ___.',
  },
  sustain: {
    core: '让状态继续维持下去。',
    image: '不是冲刺一天，而是保持三个月学习节奏。',
    breakdown: '常搭 progress, growth, effort；可表示支撑生命或系统。',
    cue: 'sustain progress',
    personalPrompt: 'To sustain progress, I need to ___.',
  },
  eliminate: {
    core: '彻底消除或淘汰。',
    image: '检查清单把重复错误一个个清掉。',
    breakdown: 'reduce 是减少；eliminate 是尽量清零。',
    cue: 'eliminate errors',
    personalPrompt: 'I want to eliminate ___ from my routine.',
  },
  assess: {
    core: '根据情况做评估判断。',
    image: '部署前先看风险、影响和回滚方案。',
    breakdown: '常搭 risk, impact, level；比 judge 更正式。',
    cue: 'assess risk',
    personalPrompt: 'Before I decide, I should assess ___.',
  },
  comply: {
    core: '遵守规则或要求。',
    image: '进入实验室前按规定戴护目镜。',
    breakdown: '固定搭配 comply with rules/law/requirements。',
    cue: 'comply with rules',
    personalPrompt: 'At work or school, I must comply with ___.',
  },
  anticipate: {
    core: '预料并提前准备。',
    image: '知道周一会忙，周日先把材料准备好。',
    breakdown: 'expect 偏“认为会发生”；anticipate 常带准备动作。',
    cue: 'anticipate demand',
    personalPrompt: 'I anticipate ___, so I will ___.',
  },
  explicit: {
    core: '明确说出，不让人猜。',
    image: '任务写清时间、格式和负责人。',
    breakdown: 'explicit 明说；implicit 暗含。',
    cue: 'explicit instruction',
    personalPrompt: 'An explicit instruction for ___ is ___.',
  },
  reluctant: {
    core: '不太愿意，但可能还是做。',
    image: '你同意发言，但心里很抗拒。',
    breakdown: '常用 reluctant to do；不是 unable，而是不情愿。',
    cue: 'reluctant to agree',
    personalPrompt: 'I am reluctant to ___ because ___.',
  },
  inherent: {
    core: '事物本身自带的。',
    image: '投资本身就有风险，不是后来才出现。',
    breakdown: '常搭 risk, value, weakness；强调内在属性。',
    cue: 'inherent risk',
    personalPrompt: 'There is inherent risk in ___.',
  },
  viable: {
    core: '现实中可行、撑得住。',
    image: '计划不只好听，还能用现有时间和钱做到。',
    breakdown: 'possible 是可能；viable 是可执行、可持续。',
    cue: 'viable option',
    personalPrompt: '___ is a viable option for me because ___.',
  },
  evaluate: {
    core: '按标准评价好坏或效果。',
    image: '老师看准确度、表达和逻辑后给分。',
    breakdown: '常搭 performance, result, option；比 estimate 更偏质量判断。',
    cue: 'evaluate performance',
    personalPrompt: 'I evaluate my progress by checking ___.',
  },
  interpret: {
    core: '解释信息背后的意思。',
    image: '看到数据上涨，分析它代表用户更活跃。',
    breakdown: '常搭 data, result, meaning；不是 translate 的逐词翻译。',
    cue: 'interpret data',
    personalPrompt: 'I interpret this result as ___.',
  },
  establish: {
    core: '建立并确立稳定状态。',
    image: '连续准时交付，慢慢建立信任。',
    breakdown: '常搭 trust, rule, system；比 start 更正式、更稳。',
    cue: 'establish trust',
    personalPrompt: 'To establish trust, I can ___.',
  },
  maintain: {
    core: '保持状态不下降。',
    image: '每天小复习，让水平不掉线。',
    breakdown: '常搭 quality, balance, standard；也可指维护设备。',
    cue: 'maintain quality',
    personalPrompt: 'I maintain my ___ by ___.',
  },
  resolve: {
    core: '解决问题或作出决定。',
    image: '团队开会把交付冲突谈清并定方案。',
    breakdown: '常搭 problem, issue, conflict；比 solve 更正式。',
    cue: 'resolve a problem',
    personalPrompt: 'To resolve ___, I should ___.',
  },
  illustrate: {
    core: '用例子或图表说明。',
    image: '一张图让复杂趋势立刻看懂。',
    breakdown: '常搭 point, idea, example；不是只表示“画插图”。',
    cue: 'illustrate a point',
    personalPrompt: 'An example that illustrates ___ is ___.',
  },
  clarify: {
    core: '把模糊内容说清楚。',
    image: '开工前确认到底谁做、何时交。',
    breakdown: '常搭 expectations, meaning, details；不是 make simple。',
    cue: 'clarify expectations',
    personalPrompt: 'I need to clarify ___ before ___.',
  },
  justify: {
    core: '说明某决定为什么合理。',
    image: '经理用成本和风险解释为什么推迟发布。',
    breakdown: '常搭 decision, cost, action；不是简单“证明是真的”。',
    cue: 'justify a decision',
    personalPrompt: 'I can justify ___ by explaining ___.',
  },
  adapt: {
    core: '适应新情况或改编内容。',
    image: '换了工作方式后，你调整学习时间。',
    breakdown: 'adapt to change；adapt a book for film 是改编。',
    cue: 'adapt to change',
    personalPrompt: 'When ___ changes, I adapt by ___.',
  },
  adjust: {
    core: '小幅调整到更合适。',
    image: '根据反馈把计划从每天两小时改成一小时。',
    breakdown: 'adjust the plan/setting；比 adapt 更具体、更小。',
    cue: 'adjust the plan',
    personalPrompt: 'I should adjust ___ after ___.',
  },
  acquire: {
    core: '获得并变成自己拥有的。',
    image: '通过阅读和练习慢慢习得新词。',
    breakdown: '常搭 knowledge, skill, company；比 get 更正式。',
    cue: 'acquire knowledge',
    personalPrompt: 'I can acquire ___ by ___.',
  },
  retain: {
    core: '保留住，不丢失。',
    image: '复习让信息留在脑子里更久。',
    breakdown: '常搭 information, memory, customers；可指记住或留住。',
    cue: 'retain information',
    personalPrompt: 'To retain ___, I need to ___.',
  },
  expand: {
    core: '扩大范围、规模或机会。',
    image: '服务从一个城市开到十个城市。',
    breakdown: '常搭 access, business, vocabulary；反义可想 reduce。',
    cue: 'expand access',
    personalPrompt: 'I want to expand my ___ by ___.',
  },
  decline: {
    core: '下降，或礼貌拒绝。',
    image: '销量连续三个月往下走。',
    breakdown: 'sales decline；decline an offer 是拒绝邀请。',
    cue: 'decline gradually',
    personalPrompt: '___ may decline if I stop ___.',
  },
  emerge: {
    core: '逐渐出现或显现。',
    image: '讨论到最后，一个新方案浮出来。',
    breakdown: '常搭 from, pattern, opportunity；不是突然跳出。',
    cue: 'emerge from',
    personalPrompt: 'A new opportunity emerged when ___.',
  },
  indicate: {
    core: '表明或指向某结论。',
    image: '数据像路标，指向用户更满意。',
    breakdown: '常搭 trend, result, need；比 show 更正式。',
    cue: 'indicate a trend',
    personalPrompt: 'These results indicate that ___.',
  },
  imply: {
    core: '不明说但暗示。',
    image: '他说“时间很紧”，暗含要删减范围。',
    breakdown: 'imply 是说话者暗示；infer 是听者推断。',
    cue: 'imply responsibility',
    personalPrompt: 'This message may imply that ___.',
  },
  reveal: {
    core: '把原来隐藏的信息显示出来。',
    image: '问卷揭示了用户真正卡在哪里。',
    breakdown: '常搭 details, truth, pattern；比 show 更有“揭开”。',
    cue: 'reveal details',
    personalPrompt: 'The feedback revealed that ___.',
  },
  submit: {
    core: '提交材料；也可表示屈服。',
    image: '周五前把报告上传到系统。',
    breakdown: '常搭 report, application, form；日常多用“提交”。',
    cue: 'submit a report',
    personalPrompt: 'I need to submit ___ by ___.',
  },
  obtain: {
    core: '通过努力或流程获得。',
    image: '先填表，再拿到审批。',
    breakdown: '常搭 approval, permission, data；比 get 更正式。',
    cue: 'obtain approval',
    personalPrompt: 'To obtain ___, I must ___.',
  },
  permit: {
    core: '允许；许可证。',
    image: '验证通过后，系统允许你进入。',
    breakdown: 'permit access；名词 permit 是许可证，重音常在前。',
    cue: 'permit access',
    personalPrompt: 'The rules permit ___ only when ___.',
  },
  prohibit: {
    core: '正式禁止。',
    image: '室内标牌写着禁止吸烟。',
    breakdown: '常搭 smoking, access, use；比 ban 更正式。',
    cue: 'prohibit smoking',
    personalPrompt: 'The policy prohibits ___ because ___.',
  },
  require: {
    core: '需要或规定必须有。',
    image: '这个问题需要马上处理。',
    breakdown: '常搭 attention, approval, evidence；比 need 更正式。',
    cue: 'require attention',
    personalPrompt: '___ requires my attention today.',
  },
  ensure: {
    core: '确保某事会发生。',
    image: '发布前检查清单保证不漏步骤。',
    breakdown: 'ensure safety/quality；不是 insure 买保险。',
    cue: 'ensure safety',
    personalPrompt: 'To ensure ___, I will ___.',
  },
  involve: {
    core: '涉及、包含或需要参与。',
    image: '新流程需要用户早期试用和反馈。',
    breakdown: '常搭 users, risk, process；involve doing 表示需要做。',
    cue: 'involve users',
    personalPrompt: 'This project will involve ___.',
  },
  affect: {
    core: '对结果产生影响。',
    image: '睡眠少，第二天表现变差。',
    breakdown: 'affect 是动词“影响”；effect 多为名词“影响/效果”。',
    cue: 'affect outcomes',
    personalPrompt: '___ can affect my performance by ___.',
  },
  impact: {
    core: '强影响或冲击。',
    image: '一次政策变化影响整个团队的节奏。',
    breakdown: '可作名词或动词；常搭 performance, cost, users。',
    cue: 'impact performance',
    personalPrompt: '___ has a clear impact on ___.',
  },
  benefit: {
    core: '受益；好处。',
    image: '每天练口语让你开会更敢说。',
    breakdown: 'benefit from practice；名词可数时指具体好处。',
    cue: 'benefit from practice',
    personalPrompt: 'I benefit from ___ because ___.',
  },
  contribute: {
    core: '贡献一部分，促成结果。',
    image: '清晰目标、稳定复习一起促成进步。',
    breakdown: 'contribute to success/problem；可正可负。',
    cue: 'contribute to success',
    personalPrompt: '___ contributes to my success in ___.',
  },
  promote: {
    core: '推动发展、提升或宣传。',
    image: '公司用活动推动新产品增长。',
    breakdown: 'promote growth/health/product；也指升职。',
    cue: 'promote growth',
    personalPrompt: 'Good feedback can promote ___.',
  },
  generate: {
    core: '产生或生成新东西。',
    image: '头脑风暴产生十个想法。',
    breakdown: '常搭 ideas, revenue, data；强调从无到有。',
    cue: 'generate ideas',
    personalPrompt: 'A discussion can generate ___ when ___.',
  },
  identify: {
    core: '识别并确认是什么。',
    image: '从错误记录里找出最常犯的语法问题。',
    breakdown: '常搭 risks, pattern, cause；比 find 更强调确认。',
    cue: 'identify risks',
    personalPrompt: 'I need to identify ___ before ___.',
  },
  recognize: {
    core: '认出；承认价值。',
    image: '你一眼认出常见句型，也认可同伴努力。',
    breakdown: 'recognize patterns/effort；可表示认知和认可。',
    cue: 'recognize patterns',
    personalPrompt: 'I can recognize ___ when I see ___.',
  },
  distinguish: {
    core: '区分相似事物。',
    image: '把 affect 和 effect 分开放进不同例句。',
    breakdown: '常用 distinguish between A and B。',
    cue: 'distinguish between',
    personalPrompt: 'I distinguish between ___ and ___ by ___.',
  },
  emphasize: {
    core: '强调重点。',
    image: '老师把考试最常见错误反复提醒。',
    breakdown: '常搭 importance, need, role；语气比 say 更强。',
    cue: 'emphasize importance',
    personalPrompt: 'I want to emphasize the importance of ___.',
  },
  recommend: {
    core: '基于判断给出建议。',
    image: '朋友问学习方法，你推荐每天短复习。',
    breakdown: 'recommend doing 或 recommend that；不要用 recommend to do。',
    cue: 'recommend an approach',
    personalPrompt: 'I recommend ___ for learners who ___.',
  },
  suggest: {
    core: '建议；也可表示数据暗示。',
    image: '你建议先改小问题；数据也显示情况在变好。',
    breakdown: 'suggest doing；data suggest 常译“表明”。',
    cue: 'suggest improvement',
    personalPrompt: 'The data suggest that ___.',
  },
  prefer: {
    core: '更喜欢某选择。',
    image: '在复杂界面和清晰界面之间，你选清晰。',
    breakdown: 'prefer A to B；prefer doing/to do 都常见。',
    cue: 'prefer clarity',
    personalPrompt: 'I prefer ___ to ___ because ___.',
  },
  compare: {
    core: '比较相同点和差异。',
    image: '把两次测验分数放一起看变化。',
    breakdown: 'compare A with/to B；重点是并排看。',
    cue: 'compare results',
    personalPrompt: 'I compare ___ with ___ to see ___.',
  },
  contrast: {
    core: '突出差异或形成对比。',
    image: '一个方案快但贵，另一个慢但便宜。',
    breakdown: 'compare 看异同；contrast 更强调不同。',
    cue: 'contrast sharply',
    personalPrompt: '___ contrasts with ___ because ___.',
  },
  predict: {
    core: '根据线索预测未来。',
    image: '模型用历史销量预测节假日需求。',
    breakdown: '常搭 demand, outcome, trend；不是 promise。',
    cue: 'predict demand',
    personalPrompt: 'I predict ___ will happen because ___.',
  },
  estimate: {
    core: '给出合理估算。',
    image: '不知道精确价格，先估个大概成本。',
    breakdown: 'estimate cost/time/number；强调不完全精确。',
    cue: 'estimate cost',
    personalPrompt: 'I estimate that ___ will take ___.',
  },
  measure: {
    core: '测量或衡量。',
    image: '用每日正确率衡量学习进步。',
    breakdown: 'measure progress/impact；名词也可指“措施”。',
    cue: 'measure progress',
    personalPrompt: 'I measure my progress by ___.',
  },
  monitor: {
    core: '持续观察变化。',
    image: '老师上课时看学生参与度有没有下降。',
    breakdown: '常搭 activity, progress, system；不是看一次就完。',
    cue: 'monitor activity',
    personalPrompt: 'I should monitor ___ every week.',
  },
  investigate: {
    core: '调查原因或事实。',
    image: '错误突然增多，团队顺着日志查原因。',
    breakdown: '常搭 causes, incident, issue；比 check 更深入。',
    cue: 'investigate causes',
    personalPrompt: 'I need to investigate why ___.',
  },
  respond: {
    core: '回应或作出反应。',
    image: '客户提问题，团队当天回复并处理。',
    breakdown: 'respond to feedback/question；response 是名词。',
    cue: 'respond quickly',
    personalPrompt: 'When someone ___, I respond by ___.',
  },
  confirm: {
    core: '确认信息是真的或无误。',
    image: '付款前再核对金额和地址。',
    breakdown: '常搭 details, booking, decision；不是 create 新信息。',
    cue: 'confirm details',
    personalPrompt: 'Before I ___, I should confirm ___.',
  },
  deny: {
    core: '否认事实或拒绝给予。',
    image: '公司说问题不是他们造成的。',
    breakdown: 'deny responsibility；deny access 是拒绝访问。',
    cue: 'deny responsibility',
    personalPrompt: 'Someone might deny ___ if ___.',
  },
  approve: {
    core: '批准；认可同意。',
    image: '主管看完申请后盖章通过。',
    breakdown: 'approve a request；approve of 表示赞成某行为。',
    cue: 'approve a request',
    personalPrompt: 'My teacher or manager may approve ___ if ___.',
  },
  reject: {
    core: '拒绝接受或驳回。',
    image: '对方礼貌地拒绝了报价。',
    breakdown: 'reject offer/request/idea；比 refuse 更常接方案和申请。',
    cue: 'reject an offer',
    personalPrompt: 'I would reject ___ if ___.',
  },
  achieve: {
    core: '通过努力达到目标。',
    image: '每天练习，最后达到目标分数。',
    breakdown: '常搭 goal, success, result；强调完成度。',
    cue: 'achieve a goal',
    personalPrompt: 'I want to achieve ___ by ___.',
  },
  pursue: {
    core: '持续追求目标或从事方向。',
    image: '决定长期走设计职业路线。',
    breakdown: 'pursue a career/goal/degree；比 chase 更正式。',
    cue: 'pursue a career',
    personalPrompt: 'I want to pursue ___ because ___.',
  },
  encourage: {
    core: '鼓励；促使某事更可能发生。',
    image: '小奖励让学生更愿意参与。',
    breakdown: 'encourage participation；可鼓励人，也可促进行为。',
    cue: 'encourage participation',
    personalPrompt: '___ encourages me to ___.',
  },
  discourage: {
    core: '使人不想做；阻止某行为。',
    image: '明确处罚让作弊变少。',
    breakdown: 'discourage cheating；也指让人灰心。',
    cue: 'discourage cheating',
    personalPrompt: '___ discourages me from ___.',
  },
  enable: {
    core: '使某人能够做某事。',
    image: '手机应用让你随时学习。',
    breakdown: 'enable access/learning；结构 enable someone to do。',
    cue: 'enable access',
    personalPrompt: 'This app enables me to ___.',
  },
  enhance: {
    core: '提高质量、效果或理解。',
    image: '例句让抽象解释更容易懂。',
    breakdown: 'enhance understanding/performance；比 improve 更正式。',
    cue: 'enhance understanding',
    personalPrompt: '___ enhances my understanding of ___.',
  },
  reduce: {
    core: '减少数量、风险或程度。',
    image: '复习清单让错误变少。',
    breakdown: 'reduce errors/cost/risk；不是完全消除。',
    cue: 'reduce errors',
    personalPrompt: 'I can reduce ___ by ___.',
  },
  increase: {
    core: '增加数量、程度或信心。',
    image: '小成功让你更敢开口说英语。',
    breakdown: 'increase confidence/speed/cost；可作动词或名词。',
    cue: 'increase confidence',
    personalPrompt: '___ increases my confidence in ___.',
  },
  exclude: {
    core: '排除，不包括。',
    image: '分析时把无关数据先去掉。',
    breakdown: 'exclude irrelevant data；反义 include。',
    cue: 'exclude irrelevant data',
    personalPrompt: 'I should exclude ___ from this list.',
  },
  include: {
    core: '包括在内。',
    image: '好笔记包含例句和常见搭配。',
    breakdown: 'include examples/details；including 后列举部分内容。',
    cue: 'include examples',
    personalPrompt: 'My notes should include ___.',
  },
  represent: {
    core: '代表某人某物；表示数据含义。',
    image: '图表中的每个点代表一个用户组。',
    breakdown: 'represent a group/value；不是 present 展示。',
    cue: 'represent a group',
    personalPrompt: 'This number represents ___.',
  },
  reflect: {
    core: '反映情况；也可反思。',
    image: '分数变化反映学习习惯变了。',
    breakdown: 'reflect a change；reflect on 是认真思考。',
    cue: 'reflect a change',
    personalPrompt: 'My recent results reflect ___.',
  },
  transfer: {
    core: '从一处转到另一处。',
    image: '把数据从旧手机传到新手机。',
    breakdown: 'transfer data/money/staff；强调位置或归属变化。',
    cue: 'transfer data',
    personalPrompt: 'I need to transfer ___ from ___ to ___.',
  },
  transform: {
    core: '彻底转变形态或状态。',
    image: '每天复习把零散词汇变成可用表达。',
    breakdown: 'transform habits/business；比 change 更强。',
    cue: 'transform habits',
    personalPrompt: 'Daily ___ can transform my ___.',
  },
  combine: {
    core: '把多个方法或部分结合。',
    image: '用听力、例句和复习一起学词。',
    breakdown: 'combine methods/data; combine A with B。',
    cue: 'combine methods',
    personalPrompt: 'I combine ___ with ___ to ___.',
  },
  separate: {
    core: '分开；区分。',
    image: '把紧急任务和重要任务分开列。',
    breakdown: 'separate tasks; separate A from B；形容词读音不同。',
    cue: 'separate tasks',
    personalPrompt: 'I separate ___ from ___ when ___.',
  },
  organize: {
    core: '整理或组织成有秩序。',
    image: '课后把笔记按主题放好。',
    breakdown: 'organize notes/event/team；可指整理物品或安排活动。',
    cue: 'organize notes',
    personalPrompt: 'I organize my ___ by ___.',
  },
  prioritize: {
    core: '按重要性排优先级。',
    image: '先处理今天必须交的任务。',
    breakdown: 'prioritize tasks/needs；不是简单喜欢哪个。',
    cue: 'prioritize tasks',
    personalPrompt: 'Today I should prioritize ___ because ___.',
  },
  focus: {
    core: '集中注意力；焦点。',
    image: '学习时关掉通知，只看一个目标。',
    breakdown: 'focus on goals；名词可指重点或焦点。',
    cue: 'focus on goals',
    personalPrompt: 'I need to focus on ___ today.',
  },
  observe: {
    core: '仔细观察；也可遵守。',
    image: '科学家记录行为变化，不急着下结论。',
    breakdown: 'observe behavior；observe rules 是遵守规则。',
    cue: 'observe behavior',
    personalPrompt: 'I observed that ___ changed when ___.',
  },
  participate: {
    core: '参与活动。',
    image: '课堂讨论时你开口贡献观点。',
    breakdown: 'participate in class/meeting；介词常用 in。',
    cue: 'participate in class',
    personalPrompt: 'I participate in ___ by ___.',
  },
  collaborate: {
    core: '与他人合作完成。',
    image: '两个人在线共写一份报告。',
    breakdown: 'collaborate with others/on a project；比 cooperate 更具体产出。',
    cue: 'collaborate with others',
    personalPrompt: 'I collaborate with ___ to ___.',
  },
  negotiate: {
    core: '协商以达成条件。',
    image: '签合同前讨论价格、时间和责任。',
    breakdown: 'negotiate terms/price；不是 argue，而是谈条件。',
    cue: 'negotiate terms',
    personalPrompt: 'I would negotiate ___ before ___.',
  },
  implement: {
    core: '把计划真正执行。',
    image: '方案定好后，团队下周开始上线。',
    breakdown: 'implement a plan/policy/system；不是只讨论。',
    cue: 'implement a plan',
    personalPrompt: 'To implement my plan, I will ___.',
  },
  operate: {
    core: '操作机器；运营系统。',
    image: '受训员工才能操作设备。',
    breakdown: 'operate a system/machine/business；强调运行和使用。',
    cue: 'operate a system',
    personalPrompt: 'Only ___ should operate ___.',
  },
  perform: {
    core: '执行任务；表现如何。',
    image: '设备自动完成重复检查。',
    breakdown: 'perform a task；perform well/badly 表示表现。',
    cue: 'perform a task',
    personalPrompt: 'I perform better when ___.',
  },
  function: {
    core: '起作用；功能。',
    image: '离线时应用仍能正常运行。',
    breakdown: 'function properly；名词 function 是功能。',
    cue: 'function properly',
    personalPrompt: 'This tool should function properly when ___.',
  },
  occur: {
    core: '发生或出现。',
    image: '初学时小错误经常出现。',
    breakdown: 'occur frequently；更正式，不用于主动“做某事”。',
    cue: 'occur frequently',
    personalPrompt: '___ often occurs when I ___.',
  },
  vary: {
    core: '因情况不同而变化。',
    image: '同一杯咖啡在不同城市价格不同。',
    breakdown: 'vary by region/person；强调不固定。',
    cue: 'vary by region',
    personalPrompt: '___ varies by ___ in my life.',
  },
  range: {
    core: '范围；从一端到另一端变化。',
    image: '分数从低到高分布在一条线上。',
    breakdown: 'range from A to B；名词是范围。',
    cue: 'range from',
    personalPrompt: 'My ___ ranges from ___ to ___.',
  },
  exceed: {
    core: '超过标准、限制或预期。',
    image: '结果比目标高出很多。',
    breakdown: 'exceed expectations/limit；比 pass 更正式。',
    cue: 'exceed expectations',
    personalPrompt: '___ exceeded my expectations because ___.',
  },
  restore: {
    core: '恢复到较好或原来状态。',
    image: '及时支持让用户重新有信心。',
    breakdown: 'restore confidence/service/file；强调找回状态。',
    cue: 'restore confidence',
    personalPrompt: 'To restore my confidence, I can ___.',
  },
  preserve: {
    core: '保护并保存原样。',
    image: '博物馆保存老照片和历史记录。',
    breakdown: 'preserve history/data/quality；比 save 更强调防止损坏。',
    cue: 'preserve history',
    personalPrompt: 'It is important to preserve ___ because ___.',
  },
  replace: {
    core: '用新的代替旧的。',
    image: '用晚间复习替代刷短视频。',
    breakdown: 'replace old habits; replace A with B。',
    cue: 'replace old habits',
    personalPrompt: 'I want to replace ___ with ___.',
  },
}
