export const originNebula: Record<string, string> = {
  explicit: '同源星云：implicit 暗含的；complicate 折在一起所以复杂；duplicate 折成两份所以复制。',
  implicit: '同源星云：explicit 展开说清；complicate 折在一起所以复杂；duplicate 折成两份所以复制。',
  complicate: '同源星云：explicit 展开说清；implicit 折在里面；duplicate 折成两份。',
  duplicate: '同源星云：explicit 展开说清；implicit 折在里面；complicate 折在一起。',
  sustain: '同源星云：tain/ten = hold。maintain 用手保持；retain 留住；obtain 拿住获得。',
  maintain: '同源星云：tain/ten = hold。sustain 从下面托住；retain 留住；obtain 拿住获得。',
  retain: '同源星云：tain/ten = hold。maintain 保持；sustain 托住维持；obtain 拿住获得。',
  obtain: '同源星云：tain/ten = hold。retain 留住；maintain 保持；sustain 托住维持。',
  submit: '同源星云：mit/miss = send。permit 放行；transmit 传送；mission 被派出去的任务。',
  permit: '同源星云：mit/miss = send。submit 往上提交；transmit 传送；mission 派出去的任务。',
  include: '同源星云：clude/close = shut。exclude 关在外面；conclude 把讨论关起来所以总结。',
  exclude: '同源星云：clude/close = shut。include 关在里面；conclude 把讨论关起来所以总结。',
  subsequent: '同源星云：sequ = follow。pursue 往前追随；sequence 一个接一个；consequence 跟着来的结果。',
  pursue: '同源星云：sequ/sue = follow。subsequent 随后跟来；sequence 顺序；consequence 后果。',
  anticipate: '同源星云：cap/cip = take。participate 拿到一份所以参与；capture 拿住捕获；capacity 能拿多少。',
  participate: '同源星云：cap/cip = take。anticipate 提前拿到/处理；capture 拿住；capacity 容量。',
  transfer: '同源星云：fer = carry。prefer 把一个选项拿到前面；refer 带回去提及；offer 拿出来给。',
  prefer: '同源星云：fer = carry。transfer 带到另一边；refer 带回去提及；offer 拿出来给。',
  reduce: '同源星云：duc/duct = lead。produce 带出来所以生产；conduct 引导进行；introduce 带进去介绍。',
  introduce: '同源星云：duc/duct = lead。reduce 带回去减少；produce 带出来生产；conduct 引导进行。',
  produce: '同源星云：duc/duct = lead。reduce 带回去减少；introduce 带进去介绍；conduct 引导进行。',
  conduct: '同源星云：duc/duct = lead。reduce 带回去减少；produce 带出来生产；introduce 带进去介绍。',
  reflect: '同源星云：flect/flex = bend。flexible 能弯；reflect 弯回去所以反射/反映。',
  flexible: '同源星云：flect/flex = bend。reflect 弯回去所以反射/反映。',
  predict: '同源星云：dict = say。dictionary 词典；contradict 反着说；indicate 是指出，不是同根但意思相近。',
  contradict: '同源星云：dict = say。predict 提前说；dictionary 收集词语。',
  dictionary: '同源星云：dict = say。predict 提前说；contradict 反着说。',
  indicate: '同源星云：dic/dicere = point/say。predict 是提前说；dedicate 原是宣布献出。',
  distinguish: '同源星云：stinguish/stinct = mark/prick。extinguish 把火标记到消失；distinct 被标出来所以不同。',
  distinct: '同源星云：distinguish 区分；extinguish 熄灭。共同感觉是“标出差别/处理掉”。',
  collaborate: '同源星云：labor = work。labor 劳动；elaborate 花工夫展开；collaborate 一起工作。',
  elaborate: '同源星云：labor = work。collaborate 一起工作；labor 劳动。',
  operate: '同源星云：opus/oper = work。operation 操作；cooperate 一起工作；operator 操作者。',
  cooperate: '同源星云：oper = work。operate 运作；operation 操作。',
  function: '同源星云：fung/funct = perform。function 履行作用；perfunctory 只做表面功夫。',
  occur: '同源星云：cur/curr = run。current 流动的；course 路线；occur 是跑到面前所以发生。',
  current: '同源星云：cur/curr = run。occur 跑到面前所以发生；course 路线。',
  restore: '同源星云：sta/st = stand。establish 让东西站稳；stable 稳定；restore 重新立起来。',
  establish: '同源星云：sta/st = stand。stable 稳定；restore 重新立起来；status 状态。',
  viable: '同源星云：viv/vit = life。vivid 有生命力般鲜明；survive 活下来；vital 生命攸关。',
  vivid: '同源星云：viv/vit = life。viable 能活；survive 活下来；vital 生命攸关。',
  survive: '同源星云：viv/vit = life。viable 能活；vivid 鲜活；vital 重要如生命。',
  vital: '同源星云：viv/vit = life。viable 能活；vivid 鲜活；survive 活下来。',
}

export function withOriginNebula(word: string, origin: string): string {
  const nebula = originNebula[word.toLowerCase()]
  return nebula ? `${origin} ${nebula}` : origin
}
