import type { VocabWord } from '../types'

type HookInput = Pick<VocabWord, 'word' | 'meaning'>

const specialHooks: Record<string, string> = {
  facilitate: 'facilitate听facility：有设施帮忙，事情就被促进。',
  constrain: 'constrain听con+strain：strain是拉紧，被拉住就是限制。',
  derive: 'derive听drive来：从来源一路开出来，得到结论。',
  coherent: 'coherent抓co+here：句子都粘在here，才连贯一致。',
  substantial: 'substantial抓substance：有实体有分量，就是大量实质的。',
  subsequent: 'subsequent抓sub+sequence：排在序列下面，就是随后。',
  allocate: 'allocate听a-locate：给资源找位置，就是分配。',
  reinforce: 'reinforce=re+force：再加一层force，就是加强。',
  undergo: 'undergo=under+go：从下面一路go过去，就是经历。',
  attribute: 'attribute听a tribute：把功劳献给某原因，就是归因。',
  encompass: 'encompass=en+compass：用圆规圈进去，就是涵盖。',
  sustain: 'sustain听死撑：一直撑住不塌，就是维持支撑。',
  eliminate: 'eliminate听移名单：从名单移掉，就是消除淘汰。',
  assess: 'assess有双ss：两次打分确认，就是评估。',
  comply: 'comply听肯配：愿意配合规则，就是遵守。',
  anticipate: 'anticipate抓anti+cipate：先在前面拦住结果，叫预料。',
  emotional: 'emotional先抓emo：人一emo，情绪化上脸。',
  ethical: 'ethical听“诶think哦”：先想该不该做，才合伦理。',
  feasible: 'feasible借possible尾巴：不只可能，是方案能落地。',
  eligible: 'eligible看e-lig-ible：能被选进名单，才有资格。',
  articulate: 'articulate抓article：表达分段成文，才清楚。',
  procurement: 'procurement抓pro和cure：为公司把物资搞到手。',
  precedent: 'precedent抓pre在前：前面的案例，后面照着判。',
  sanction: 'sanction借section看条款：allow批准，ban制裁。',
  substantiate: 'substantiate抓substance：证据让空话有实体。',
  explicit: 'explicit抓ex往外：话全说到外面，明确。',
  implicit: 'implicit抓im往里：意思藏里面，暗含。',
  imply: 'imply抓in心里：话不说破，只暗示。',
  reluctant: 'reluctant听re+luctant：人被拉回来，不情愿往前。',
  inherent: 'inherent=in+here：本来就在这里面，是固有内在的。',
  viable: 'viable听via+able：有路可走且能活，就是可行。',
  evaluate: 'evaluate抓value：给价值打分，就是评价估计。',
  interpret: 'interpret听into+pret：把内容转进脑内，就是解释理解。',
  establish: 'establish听stable：让东西站稳，就是建立确立。',
  maintain: 'maintain抓main+tain：把主状态拴住，就是维持。',
  resolve: 'resolve=re+solve：重新solve问题，就是解决。',
  illustrate: 'illustrate听illustration：用图例把观点说明白。',
  clarify: 'clarify抓clear：让话变clear，就是澄清。',
  justify: 'justify抓just：说得just公平合理，就是证明合理。',
  adapt: 'adapt听adopt改一字：拿来再改，就是适应改编。',
  adjust: 'adjust抓just：调到just right，就是调整。',
  acquire: 'acquire听啊快拿：把知识拿到手，就是获得。',
  retain: 'retain=re+tain：再次抓住不放，就是保留记住。',
  expand: 'expand=ex+pand：往外铺开，就是扩大。',
  decline: 'decline=de+cline：线往下走，也可拒绝。',
  emerge: 'emerge听一merge：从水里冒出并显现。',
  indicate: 'indicate抓index指针：亮出方向，表示结果。',
  reveal: 'reveal听re+veil：把面纱掀开，就是揭示。',
  submit: 'submit=sub+mit：把材料放到下面交上去，就是提交。',
  obtain: 'obtain=ob+tain：把东西抓到手，就是获得。',
  permit: 'permit听批门票：票给了，门就允许进。',
  prohibit: 'prohibit抓hibit听hold住：规则按住行为，禁止。',
  require: 'require=re+quire：任务反复追问你要什么，就是要求。',
  ensure: 'ensure=en+sure：让事情sure，就是确保。',
  involve: 'involve=in+volve：卷进去，就是涉及包含。',
  affect: 'affect=a+effect：对结果产生effect，就是影响。',
  impact: 'impact=im+pact：力量打进pact里，就是冲击影响。',
  benefit: 'benefit听benefit本身：好处fit到你身上，就是受益。',
  contribute: 'contribute=con+tribute：大家一起投一份，就是贡献。',
  promote: 'promote=pro+mote：往前推一步，就是促进提升。',
  generate: 'generate抓generator：机器一开就生成产生。',
  identify: 'identify抓identity：认出身份，就是识别确认。',
  recognize: 'recognize=re+cognize：再次认出来，就是认可认出。',
  distinguish: 'distinguish听distinct：把相似项分清，就是区分。',
  emphasize: 'emphasize抓emphasis：把重点加重，就是强调。',
  recommend: 'recommend=re+commend：再次郑重建议，就是推荐。',
  suggest: 'suggest听稍举手：轻轻举手提出，就是建议。',
  prefer: 'prefer=pre+fer：心里先选前一个，就是更喜欢。',
  compare: 'compare=com+pair：把两项配成一对，就是比较。',
  contrast: 'contrast=contra+st：相反站着，就是对比。',
  predict: 'predict=pre+dict：提前说出来，就是预测。',
  estimate: 'estimate听estimate里有mate：让同伴帮你估计。',
  measure: 'measure听measure尺：拿尺量，就是测量衡量。',
  monitor: 'monitor看monitor屏：盯屏幕，就是监控观察。',
  investigate: 'investigate抓in+vest：穿上调查背心进去查。',
  respond: 'respond=re+spond：对声音再回过去，就是回应。',
  confirm: 'confirm=con+firm：一起把信息变firm，就是确认。',
  deny: 'deny听抵赖：说不是我，就是否认拒绝。',
  approve: 'approve=ap+prove：证明通过，就是批准赞成。',
  reject: 'reject=re+ject：把东西ject扔回去，就是拒绝。',
  achieve: 'achieve听啊取到：目标终于取到，就是实现。',
  pursue: 'pursue听扑追：扑出去追，就是追求。',
  encourage: 'encourage=en+courage：把勇气放进去，就是鼓励。',
  discourage: 'discourage=dis+courage：把勇气拿掉，就是使灰心。',
  enable: 'enable=en+able：让人able能做，就是使能够。',
  enhance: 'enhance=en+hance：把程度往上加，就是增强。',
  reduce: 'reduce=re+duce：把数量往回带低，就是减少。',
  increase: 'increase=in+crease：刻度往里挤高，就是增加。',
  exclude: 'exclude=ex+clude：关到外面，就是排除。',
  include: 'include=in+clude：关到里面，就是包括。',
  represent: 'represent=re+present：把一群人呈现出来，就是代表。',
  reflect: 'reflect=re+flect：光线弯回来，就是反映反思。',
  transfer: 'transfer=trans+fer：跨过去搬走，就是转移。',
  transform: 'transform=trans+form：跨过去换形态，就是转变。',
  combine: 'combine=com+bine：绑在一起，就是组合。',
  separate: 'separate听separate有part味：拆成部分，就是分开。',
  organize: 'organize抓organ：器官各就位，就是组织整理。',
  prioritize: 'prioritize抓priority：把优先级排前，就是优先处理。',
  observe: 'observe=ob+serve：守着看，就是观察遵守。',
  participate: 'participate抓part：拿一部分加入，就是参与。',
  collaborate: 'collaborate=co+labor：一起劳动，就是合作。',
  negotiate: 'negotiate听ne-go：你来我往谈条件，就是协商。',
  implement: 'implement抓implement工具：拿工具把计划执行。',
  operate: 'operate抓operator：操作员让系统运行。',
  perform: 'perform=per+form：把形式做出来，就是执行表现。',
  function: 'function抓function键：按下有功能，系统起作用。',
  occur: 'occur听哦！occur：事情突然出现发生。',
  vary: 'vary听very变：各处都变，就是不同。',
  range: 'range抓range范围：从低到高一排，就是范围。',
  exceed: 'exceed=ex+ceed：走出上限，就是超过。',
  restore: 'restore=re+store：把状态存回去，就是恢复。',
  preserve: 'preserve=pre+serve：提前守住，就是保护保存。',
  replace: 'replace=re+place：重新放位置，就是替换。',
  mitigate: 'mitigate听mini-gate：把大风险缩小，就是减轻。',
  validate: 'validate看valid：valid是有效，用数据证明有效。',
  infer: 'infer听in+fer：从里面线索推出结论。',
  synthesize: 'synthesize抓synthetic合成：把材料合成综合。',
  scrutinize: 'scrutinize抓scrutiny：拿放大镜仔细审查。',
  formulate: 'formulate抓form：把想法做成公式，就是制定。',
  leverage: 'leverage抓lever杠杆：借力放大，就是利用。',
  align: 'align=a+line：排成一条线，就是对齐一致。',
  quantify: 'quantify抓quantity：把事情变数量，就是量化。',
  mandate: 'mandate抓mand命令：日期被命令钉住，必须执行。',
  reconcile: 'reconcile=re+concile：把冲突重新拉到一起，就是调和。',
  refine: 'refine=re+fine：再次打磨到fine，就是改进精炼。',
  diversify: 'diversify抓diverse：让种类变多，就是多样化。',
  disclose: 'disclose=dis+close：把关着的打开，就是披露。',
  undermine: 'undermine=under+mine：从下面挖矿，暗中削弱。',
  offset: 'offset=off+set：把一边设成抵消，就是弥补。',
  convey: 'convey听传vey：把信息传过去，就是传达运输。',
  elaborate: 'elaborate抓labor：下功夫加工细节，就是详述。',
  underscore: 'underscore=under+score：在下面划线，就是强调。',
  depict: 'depict抓picture：用图画出来，就是描绘。',
  capture: 'capture抓cap抓住：把重点抓住，就是捕捉表达。',
  navigate: 'navigate抓nav导航：在复杂路里找方向。',
  cultivate: 'cultivate抓culture近形：文化能力要长期培养。',
  compelling: 'compelling抓compel：证据强到逼你信服。',
  ambiguous: 'ambiguous听两边amb：左右都说得通，就是含糊。',
  concise: 'concise听砍size：把废话砍小，就是简明。',
  robust: 'robust听肉boost：身体被boost，系统很稳健。',
  plausible: 'plausible听applause：听着能鼓掌，貌似合理。',
  tentative: 'tentative抓tent试搭帐篷：先临时试一下，暂定。',
  precise: 'precise=pre+cise：先切准位置，就是精确。',
  notable: 'notable=note+able：值得被记笔记，就是显著。',
  deviate: 'deviate=de+via：离开路线via，就是偏离。',
  integrate: 'integrate抓integer完整：合成一个整体，就是整合。',
  perceive: 'perceive听perceive里receive：接收到感觉，就是感知。',
  trigger: 'trigger听扳机trigger：一扣就触发事件。',
  contradict: 'contradict=contra+dict：说出相反话，就是反驳矛盾。',
  revenue: 'revenue听re+venue：钱又回到场馆，就是收入。',
  margin: 'margin抓margin页边：剩下的边，就是利润余地。',
  forecast: 'forecast=fore+cast：提前投出判断，就是预测预报。',
  liquidity: 'liquidity抓liquid液体：钱能流动，就是变现能力。',
  inventory: 'inventory抓invent+ory：盘点造册，就是库存清单。',
  stakeholder: 'stakeholder=stake+holder：握着利益桩的人，利益相关。',
  benchmark: 'benchmark=bench+mark：板凳上刻标准线，就是基准。',
  portfolio: 'portfolio=port+folio：随身带的一叠作品，就是组合。',
  roadmap: 'roadmap=road+map：路线地图，就是规划。',
  scalable: 'scalable=scale+able：规模能放大，就是可扩展。',
  retention: 'retention=re+tain+tion：抓住用户不走，就是留存。',
  churn: 'churn听搅 churn：客户被搅走，就是流失。',
  conversion: 'conversion=convert+sion：转成另一状态，就是转化。',
  pipeline: 'pipeline=pipe+line：机会沿管线走，就是流程线。',
  capacity: 'capacity抓cap容量：杯盖下能装多少，就是能力容量。',
  throughput: 'throughput=through+put：放进去穿过去，就是处理量。',
  backlog: 'backlog=back+log：背后日志堆着，就是积压待办。',
  budget: 'budget听不准花：钱有限额，就是预算。',
  incentive: 'incentive听in+cent：把钱放进去激励你。',
  compliance: 'compliance抓comply：配合规则的状态，就是合规。',
  methodology: 'methodology=method+ology：研究方法那一套。',
  empirical: 'empirical听experience：靠经验观察数据，不靠空想。',
  framework: 'framework=frame+work：工作先搭框，就是体系。',
  variable: 'variable=vary+able：能够变化的量，就是变量。',
  hypothesis: 'hypothesis听high thesis：高高挂着待验证的假设。',
  correlate: 'correlate=co+relate：两件事一起相关。',
  bias: 'bias听歪bias：尺子歪了，判断有偏差。',
  sample: 'sample听sample样品：取一小份代表整体。',
  criterion: 'criterion听criteria单数：一个判断标准。',
  rigorous: 'rigorous听rigor严格：每步都拧紧，才严谨。',
  preliminary: 'preliminary=pre+limit：正式前的初步边界。',
  literature: 'literature抓liter字母文字：论文文献都在文字里。',
  citation: 'citation=cite+tion：把来源cite出来，就是引用。',
  thesis: 'thesis听题是：论文要证明的题，就是论点。',
  premise: 'premise=pre+mise：先摆在前面的条件，就是前提。',
  refute: 'refute=re+fight：回头打掉论点，就是驳斥。',
  qualitative: 'qualitative=quality+ive：看性质质量，不看数字。',
  consistent: 'consistent=con+sist：一直站在一起，就是一致稳定。',
  aggregate: 'aggregate抓greg群：数据成群聚合，就是汇总。',
  annotate: 'annotate=add+note：给旁边加note，就是注释。',
  statute: 'statute抓statue站着：站稳的成文法规。',
  ordinance: 'ordinance听order：地方order写成条例。',
  jurisdiction: 'jurisdiction=juris+diction：法律说话的范围，就是管辖权。',
  litigation: 'litigation听legal行动：进法律程序，就是诉讼。',
  oversight: 'oversight=over+sight：从上面看，就是监督；漏看也叫疏忽。',
  accountability: 'accountability=account+ability：能被算账，就是问责。',
  transparency: 'transparency=trans+appear：透过去能看见，就是透明。',
  enforcement: 'enforcement=en+force+ment：把force执行出来。',
  amendment: 'amendment=amend+ment：修改动作变成修正案。',
  referendum: 'referendum抓refer：把问题交回人民投票。',
  constituency: 'constituency抓constituent：选民组成的区域。',
  bureaucracy: 'bureaucracy抓bureau办公室：办公室层层规则，就是官僚。',
  governance: 'governance抓govern：治理这件事的机制。',
  protocol: 'protocol抓pro+tocol：按步骤往前走的规程。',
  provision: 'provision=provide+sion：提供出来的条款或供应。',
  exemption: 'exemption=ex+empt：从规则里拿空出来，就是豁免。',
  allegation: 'allegation抓allege：还没证实的指控。',
  impartial: 'impartial=im+partial：不站partial一边，就是公正。',
  abundant: 'abundant听a-bund：一捆又一捆，多到丰富。',
  scarce: 'scarce听scare：资源少到让人慌，就是稀缺。',
  adverse: 'adverse=ad+verse：方向反着来，就是不利。',
  mutual: 'mutual听me too all：双方都参与，就是相互的。',
  relevant: 'relevant听relate：能关联到题目，就是相关。',
  redundant: 'redundant=re+dundant：重复多出来，就是冗余。',
  accurate: 'accurate抓curate细挑：反复校准后准确。',
  efficient: 'efficient抓effect：用少资源做出效果，就是高效。',
  flexible: 'flexible=flex+ible：能弯能调，就是灵活。',
  stable: 'stable听stay-able：能一直stay住，就是稳定。',
  dynamic: 'dynamic抓dynamo发电：一直有动力变化。',
  dominant: 'dominant抓dominate：压过别人，占主导。',
  complex: 'complex=com+plex：很多线编在一起，就是复杂。',
  diverse: 'diverse=di+verse：走向不同，就是多样。',
  corporate: 'corporate抓corp公司体：公司整体层面的。',
  regulatory: 'regulatory抓regulate：用规则管住，就是监管的。',
  strategic: 'strategic抓strategy：服务长期策略，就是战略性。',
  operational: 'operational=operate+tional：日常运作层面的。',
  administrative: 'administrative抓admin：后台管理手续，就是行政的。',
  financial: 'financial抓finance：钱和资金这一层，就是财务的。',
  fiscal: 'fiscal听fiscus国库：政府钱袋，就是财政的。',
  monetary: 'monetary抓money：货币和利率这一层。',
  technical: 'technical抓tech：技术细节相关的。',
  digital: 'digital抓digit数字：数字化的，进屏幕系统。',
  virtual: 'virtual听VR：不在现场但功能有效，就是虚拟。',
  physical: 'physical抓physic身体物理：能摸到的实体层。',
  cognitive: 'cognitive抓cognition认知：脑子处理信息的。',
  cultural: 'cultural抓culture：群体习惯背景，就是文化的。',
  environmental: 'environmental抓environment：周围环境相关的。',
  sustainable: 'sustainable=sustain+able：能长期撑住，就是可持续。',
  renewable: 'renewable=re+new+able：能重新变新，就是可再生。',
  temporary: 'temporary抓temp时间：只管一段时间，就是临时。',
  permanent: 'permanent抓remain味：一直留下，就是永久。',
  voluntary: 'voluntary抓volunt意愿：自己愿意，就是自愿。',
  mandatory: 'mandatory抓mandate命令：被命令必须做，就是强制。',
  confidential: 'confidential抓confidence信任：只给信任范围看。',
  transparent: 'transparent=trans+parent：透过去看得清，就是透明。',
  reliable: 'reliable=rely+able：能依靠，就是可靠。',
  crucial: 'crucial听crux核心：卡在核心处，就是关键。',
  fundamental: 'fundamental抓fund基础：底层基础，就是根本。',
  typical: 'typical抓type类型：代表这一类，就是典型。',
  exceptional: 'exceptional=exception+al：例外级别，就是异常杰出。',
  gradual: 'gradual抓grade级：一级一级变，就是逐渐。',
  rapid: 'rapid听rapid快：速度快，变化迅速。',
  rare: 'rare听rare稀：出现次数很少，就是罕见。',
  severe: 'severe听sever切断：严重到要切开处理。',
  broad: 'broad听board大板：范围铺得宽，就是广泛。',
  narrow: 'narrow听narrow窄：范围收紧，就是狭窄。',
  visible: 'visible=vision+ible：能被看见，就是可见。',
  capable: 'capable=cap+able：脑袋有容量能做，就是有能力。',
  liable: 'liable=lie+able：说错话可能担责，就是有法律责任。',
  potential: 'potential抓potent力量：里面有潜在力量。',
  apparent: 'apparent=appear+ent：看起来已经出现，就是明显。',
  evident: 'evident=e+vid看：看出来的证据，就是明显。',
  comprehensive: 'comprehensive=com+prehend：一起抓住全貌，就是全面。',
  specific: 'specific抓spec种类：指定某一项，就是具体。',
  primary: 'primary抓prime第一：排第一，就是主要。',
  secondary: 'secondary抓second：第二层，就是次要。',
  initial: 'initial抓init开始：开头那一下，就是最初。',
  overall: 'overall=over+all：盖住全部，就是总体。',
  parallel: 'parallel抓para旁边：两条线并排，就是平行。',
  alternative: 'alternative抓alternate轮换：另一条可选路。',
  compatible: 'compatible=com+patible：能一起配合不冲突。',
  sufficient: 'sufficient听suffice：够用了，就是充分。',
  excessive: 'excessive=excess+ive：超过需要，就是过度。',
  moderate: 'moderate抓mode中间档：调到适中，就是中等。',
  intense: 'intense=in+tense：里面绷紧，就是强烈紧张。',
  volatile: 'volatile听fly：飞来飞去不稳定，就是易变。',
  resilient: 'resilient听re-spring：重新弹回，就是有韧性。',
  vulnerable: 'vulnerable抓wound伤口：容易受伤，就是脆弱。',
  practical: 'practical抓practice：能实践，就是实际实用。',
  theoretical: 'theoretical抓theory：停在理论层，就是理论的。',
  abstract: 'abstract=abs+tract：从实体抽走，就是抽象。',
  concrete: 'concrete抓concrete混凝土：实体硬块，就是具体。',
  rational: 'rational抓ratio理由：有理由计算，就是理性。',
  logical: 'logical抓logic：推理接得上，就是合逻辑。',
  neutral: 'neutral抓neither：两边都不站，就是中立。',
  internal: 'internal=in+ternal：往里面，就是内部的。',
  external: 'external=ex+ternal：往外面，就是外部的。',
  adjacent: 'adjacent=ad+jacent：贴到旁边，就是相邻。',
  equivalent: 'equivalent抓equal+value：价值相等，就是等同。',
  concurrent: 'concurrent=con+current：一起流动，就是同时发生。',
  persistent: 'persistent=per+sist：一直站住不退，就是持续。',
  subordinate: 'subordinate=sub+order：排在下面，就是下级。',
  autonomous: 'autonomous抓auto自己：自己管自己，就是自主。',
  inclusive: 'inclusive=in+clude：关进来，就是包容包含。',
  exclusive: 'exclusive=ex+clude：关出去，就是排他独有。',
  consecutive: 'consecutive抓sequence：一个接一个，就是连续。',
  simultaneous: 'simultaneous抓simul同一时刻：同时发生。',
  prospective: 'prospective=pro+spect：向前看，就是未来潜在。',
  retrospective: 'retrospective=retro+spect：向后看，就是回顾。',
  analytical: 'analytical抓analysis：拆开分析，就是分析的。',
  conventional: 'conventional抓convention：大家惯用，就是常规传统。',
  innovative: 'innovative抓innovate：引入new办法，就是创新。',
  arbitrary: 'arbitrary听arbiter裁判：个人随口裁，就是武断。',
  legitimate: 'legitimate抓legit：合法靠谱，就是正当。',
}

const moduleRules: Array<{
  pattern: RegExp
  hook: (word: string, meaning: string) => string
}> = [
  { pattern: /tional$/, hook: (word, meaning) => `${word}=${word.slice(0, -5)}+tional：动作状态变形容词，连到${meaning}。` },
  { pattern: /able$/, hook: (word, meaning) => `${word}=${word.slice(0, -4)}+able：able是能，连到${meaning}。` },
  { pattern: /ible$/, hook: (word, meaning) => `${word}=${word.slice(0, -4)}+ible：ible当able，连到${meaning}。` },
  { pattern: /ment$/, hook: (word, meaning) => `${word}=${word.slice(0, -4)}+ment：动作留下结果，连到${meaning}。` },
  { pattern: /tion$/, hook: (word, meaning) => `${word}=${word.slice(0, -4)}+tion：动作变名词，连到${meaning}。` },
  { pattern: /sion$/, hook: (word, meaning) => `${word}=${word.slice(0, -4)}+sion：动作有结果，连到${meaning}。` },
  { pattern: /ity$/, hook: (word, meaning) => `${word}=${word.slice(0, -3)}+ity：性质状态，连到${meaning}。` },
  { pattern: /ive$/, hook: (word, meaning) => `${word}=${word.slice(0, -3)}+ive：带这种倾向，连到${meaning}。` },
  { pattern: /al$/, hook: (word, meaning) => `${word}=${word.slice(0, -2)}+al：变形容词，连到${meaning}。` },
  { pattern: /ize$/, hook: (word, meaning) => `${word}=${word.slice(0, -3)}+ize：把它做成，连到${meaning}。` },
  { pattern: /fy$/, hook: (word, meaning) => `${word}=${word.slice(0, -2)}+fy：让它变成，连到${meaning}。` },
  { pattern: /^re/, hook: (word, meaning) => `${word}=re+${word.slice(2)}：re当再次回头，连到${meaning}。` },
  { pattern: /^pre/, hook: (word, meaning) => `${word}=pre+${word.slice(3)}：pre在前，连到${meaning}。` },
  { pattern: /^pro/, hook: (word, meaning) => `${word}=pro+${word.slice(3)}：pro往前，连到${meaning}。` },
  { pattern: /^sub/, hook: (word, meaning) => `${word}=sub+${word.slice(3)}：sub在下面，连到${meaning}。` },
  { pattern: /^trans/, hook: (word, meaning) => `${word}=trans+${word.slice(5)}：trans跨过去，连到${meaning}。` },
  { pattern: /form/, hook: (word, meaning) => `${word}抓form：形态被处理，连到${meaning}。` },
  { pattern: /port/, hook: (word, meaning) => `${word}抓port：东西被带走，连到${meaning}。` },
  { pattern: /press/, hook: (word, meaning) => `${word}抓press：压力压出来，连到${meaning}。` },
  { pattern: /sign/, hook: (word, meaning) => `${word}抓sign：信号或标记，连到${meaning}。` },
  { pattern: /dict/, hook: (word, meaning) => `${word}抓dict：说出来判断，连到${meaning}。` },
  { pattern: /spect|scrut/, hook: (word, meaning) => `${word}抓spect看：盯住看，连到${meaning}。` },
  { pattern: /serve/, hook: (word, meaning) => `${word}抓serve：保住或服务，连到${meaning}。` },
  { pattern: /value|valid/, hook: (word, meaning) => `${word}抓value/valid：判断价值，连到${meaning}。` },
]

function firstMeaning(meaning: string): string {
  return meaning
    .split(/[；;，,]/)[0]
    .replace(/[。.!！]/g, '')
    .trim()
    .slice(0, 10)
}

function trimHook(hook: string): string {
  const cleaned = hook
    .replace(/抓(?=[A-Za-z])/g, '看')
    .replace(/，就是/g, '，')
    .replace(/就是/g, '')
    .replace(/，叫/g, '，')
    .replace(/叫/g, '')
    .replace(/。。+/g, '。')
  return cleaned.length <= 56 ? cleaned : `${cleaned.slice(0, 55)}。`
}

function hasWordShapeBridge(word: string, hook: string): boolean {
  const lower = hook.toLowerCase()
  const normalized = word.toLowerCase()
  if (/像|想/.test(hook) && !/借|看|听|先认/.test(hook)) return false
  return (lower.includes(normalized) || lower.includes(normalized.slice(0, 4)))
    && /借|看|听|先认/.test(hook)
}

export function buildWordShapeHook(input: HookInput, fallback?: string): string {
  const word = input.word.toLowerCase()
  const meaning = firstMeaning(input.meaning)
  const special = specialHooks[word]
  if (special) return trimHook(special)

  const rule = moduleRules.find((item) => item.pattern.test(word))
  if (rule) return trimHook(rule.hook(input.word, meaning))

  if (fallback && !/像|就是|意思/.test(fallback) && hasWordShapeBridge(word, fallback)) {
    return trimHook(fallback)
  }

  const head = input.word.slice(0, Math.min(5, input.word.length))
  return trimHook(`${input.word}先认${head}：先钉住开头拼写，再接${meaning}。`)
}
