export const wordOrigins: Record<string, string> = {
  facilitate: '词源：来自拉丁 facilis，意思是 easy、容易；所以核心是“让事情变容易”。',
  constrain: '词源：来自拉丁 constringere，意思是 tie tightly、紧紧束住；所以是被条件绑住。',
  derive: '词源：来自拉丁 derivare，原意是 draw off water、把水从源头引出；引申为“源自”。',
  coherent: '词源：来自拉丁 cohaerere，意思是 stick together、粘在一起；所以是逻辑黏合。',
  substantial: '词源：来自拉丁 substantia，意思是 substance、本质或实体；所以强调“有实质分量”。',
  subsequent: '词源：来自拉丁 subsequi，sub 是 after，sequi 是 follow；所以是“随后跟来的”。',
  allocate: '词源：来自拉丁 allocare，ad 是 to，locare 是 place；原意是“放到某个位置”。',
  reinforce: '词源：来自 re- again 和 enforce/force；就是再次加力，让东西更牢。',
  undergo: '词源：古英语 under + go，原意是 go under、经历/承受某过程。',
  attribute: '词源：来自拉丁 attribuere，ad 是 to，tribuere 是 assign/give；把原因分派给某事。',
  encompass: '词源：en- 是 put into，compass 是 circle/range；原意像“圈进范围里”。',
  sustain: '词源：来自拉丁 sustinere，sub 是 from below，tenere 是 hold；从下面托住、维持。',
  eliminate: '词源：来自拉丁 eliminare，e/ex 是 out，limen 是 threshold；原意是赶出门槛外。',
  assess: '词源：来自拉丁 assidere，ad 是 beside，sedere 是 sit；原意是坐在旁边估价/判断。',
  comply: '词源：来自拉丁 complere，com 是 together，plere 是 fill；后来变成“按要求完成”。',
  anticipate: '词源：来自拉丁 anticipare，ante 是 before，capere 是 take；原意是“提前拿到/提前处理”。',
  explicit: '词源：来自拉丁 explicare，ex 是 out，plicare 是 fold；把折起来的东西展开，所以是说清楚。',
  reluctant: '词源：来自拉丁 reluctari，re 是 against，luctari 是 struggle；内心在抵抗。',
  inherent: '词源：来自拉丁 inhaerere，in 是 in，haerere 是 stick；原意是粘在里面，自带的。',
  viable: '词源：来自法语 vie/拉丁 vita，意思是 life；viable 原指能活，后指方案能活下去。',
  evaluate: '词源：来自 value，加 e-/ex 的“给出价值”；所以是判断价值高低。',
  interpret: '词源：来自拉丁 interpretari，原指解释者/中介；把信息转成可理解意思。',
  establish: '词源：来自拉丁 stabilire，stable 是稳定；establish 就是让东西稳定站住。',
  maintain: '词源：来自拉丁 manu tenere，manu 是 hand，tenere 是 hold；用手保持住。',
  resolve: '词源：来自拉丁 resolvere，re 是 back，solvere 是 loosen；把结解开。',
  illustrate: '词源：来自拉丁 illustrare，lustr/luce 有 light；用例子把意思照亮。',
  clarify: '词源：来自拉丁 clarus，意思是 clear、明亮清楚；clarify 是让它清楚。',
  justify: '词源：来自拉丁 justus，意思是 just/right；justify 是说明某事是合理的。',
  adapt: '词源：来自拉丁 adaptare，ad 是 to，aptare 是 fit；调到适合新情况。',
  adjust: '词源：来自古法语 ajuster，a 是 to，juste 是 right/exact；调到刚好。',
  acquire: '词源：来自拉丁 acquirere，ad 是 to，quaerere 是 seek；通过寻找而获得。',
  retain: '词源：来自拉丁 retinere，re 是 back，tenere 是 hold；把东西留住。',
  expand: '词源：来自拉丁 expandere，ex 是 out，pandere 是 spread；向外展开。',
  decline: '词源：来自拉丁 declinare，de 是 down，clinare 是 bend；向下倾斜，引申为下降。',
  emerge: '词源：来自拉丁 emergere，e 是 out，mergere 是 dip/sink；从水下冒出来。',
  indicate: '词源：来自拉丁 indicare，in 是 toward，dicare 是 point out；指出、表明。',
  imply: '词源：来自拉丁 implicare，in 是 in，plicare 是 fold；把意思折在里面，不明说。',
  reveal: '词源：来自拉丁 revelare，re 是 back，velum 是 veil；把面纱揭开。',
  submit: '词源：来自拉丁 submittere，sub 是 under，mittere 是 send；送到下面/提交。',
  obtain: '词源：来自拉丁 obtinere，ob 是 toward，tenere 是 hold；拿住、获得。',
  permit: '词源：来自拉丁 permittere，per 是 through，mittere 是 send/let go；放行、允许通过。',
  prohibit: '词源：来自拉丁 prohibere，pro 是 forward，habere 是 hold；挡在前面不让做。',
  require: '词源：来自拉丁 requirere，re 是 again，quaerere 是 seek/ask；反复要求、需要。',
  ensure: '词源：来自 en- make 和 sure；让某事变得确定。',
  involve: '词源：来自拉丁 involvere，in 是 in，volvere 是 roll；卷进去，所以是涉及。',
  affect: '词源：来自拉丁 afficere，ad 是 to，facere 是 do/make；对某物产生作用。',
  impact: '词源：来自拉丁 impingere，in 是 into，pangere 是 strike/fix；撞上去产生影响。',
  benefit: '词源：来自拉丁 bene facere，bene 是 well，facere 是 do；做好事、带来好处。',
  contribute: '词源：来自拉丁 contribuere，con 是 together，tribuere 是 give；一起给出一份。',
  promote: '词源：来自拉丁 promovere，pro 是 forward，movere 是 move；向前推动。',
  generate: '词源：来自拉丁 generare，genus/gener 是 birth/kind；生出、产生。',
  identify: '词源：来自 idem，意思是 same；identify 是确认“这就是同一个东西”。',
  recognize: '词源：来自拉丁 recognoscere，re 是 again，cognoscere 是 know；再次认出。',
  distinguish: '词源：来自拉丁 distinguere，dis 是 apart，stinguere 是 mark；标出来分开。',
  emphasize: '词源：来自希腊 emphasis，en 是 in，phainein 是 show；把重点显示出来。',
  recommend: '词源：来自拉丁 recommendare，re 是 again，commendare 是 entrust/praise；郑重托付推荐。',
  suggest: '词源：来自拉丁 suggerere，sub 是 from below，gerere 是 carry；从下面送上一个想法。',
  prefer: '词源：来自拉丁 praeferre，prae 是 before，ferre 是 carry；把一个选项放到前面。',
  compare: '词源：来自拉丁 comparare，com 是 together，par 是 equal；放在一起看是否相等。',
  contrast: '词源：来自拉丁 contra stare，contra 是 against，stare 是 stand；相对站立形成差异。',
  predict: '词源：来自拉丁 praedicere，prae 是 before，dicere 是 say；提前说出。',
  estimate: '词源：来自拉丁 aestimare，意思是 value/appraise；给出价值或数量判断。',
  measure: '词源：来自拉丁 mensura，意思是 measurement；用尺度衡量。',
  monitor: '词源：来自拉丁 monere，意思是 warn/remind；原意是提醒观察的人。',
  investigate: '词源：来自拉丁 investigare，in 是 in，vestigium 是 footprint；沿着足迹追查。',
  respond: '词源：来自拉丁 respondere，re 是 back，spondere 是 pledge/answer；回给答案。',
  confirm: '词源：来自拉丁 confirmare，con 是 together，firmare 是 strengthen；让事情更确定。',
  deny: '词源：来自拉丁 denegare，de 是 away，negare 是 say no；明确说不。',
  approve: '词源：来自拉丁 approbare，ad 是 to，probare 是 test/prove；测试后认可。',
  reject: '词源：来自拉丁 reicere，re 是 back，iacere 是 throw；扔回去、拒绝。',
  achieve: '词源：来自古法语 achever，来自 chef/head；做到终点、完成。',
  pursue: '词源：来自拉丁 prosequi，pro 是 forward，sequi 是 follow；向前追随目标。',
  encourage: '词源：来自 en- make 和 courage；让人有勇气。',
  discourage: '词源：dis- 表示 away/opposite，加 courage；拿走勇气，使人不想做。',
  enable: '词源：en- 是 make，able 是 able；使某人能够。',
  enhance: '词源：来自古法语 enhaucier，意思是 raise higher；把水平抬高。',
  reduce: '词源：来自拉丁 reducere，re 是 back，ducere 是 lead；带回较小状态。',
  increase: '词源：来自拉丁 increscere，in 是 in，crescere 是 grow；增长起来。',
  exclude: '词源：来自拉丁 excludere，ex 是 out，claudere 是 shut；关在外面。',
  include: '词源：来自拉丁 includere，in 是 in，claudere 是 shut；关在里面、包括。',
  represent: '词源：来自拉丁 repraesentare，re 是 again，praesentare 是 present；再次呈现、代表。',
  reflect: '词源：来自拉丁 reflectere，re 是 back，flectere 是 bend；弯回去、反射。',
  transfer: '词源：来自拉丁 transferre，trans 是 across，ferre 是 carry；带到另一边。',
  transform: '词源：来自拉丁 transformare，trans 是 across，forma 是 shape；改变形状。',
  combine: '词源：来自拉丁 combinare，com 是 together，bini 是 two by two；合在一起。',
  separate: '词源：来自拉丁 separare，se 是 apart，parare 是 prepare/set；分开放置。',
  organize: '词源：来自希腊 organon，意思是 tool/instrument；把部分安排成可运作的系统。',
  prioritize: '词源：来自 prior，意思是 earlier/former；把某事放到更前面。',
  focus: '词源：来自拉丁 focus，原意是 hearth/fireplace；后来指光线或注意力的集中点。',
  observe: '词源：来自拉丁 observare，ob 是 toward，servare 是 watch/keep；注意看并遵守。',
  participate: '词源：来自拉丁 participare，pars 是 part，capere 是 take；拿到一份、参与其中。',
  collaborate: '词源：来自拉丁 collaborare，com 是 together，laborare 是 work；一起工作。',
  negotiate: '词源：来自拉丁 negotium，nec 是 not，otium 是 leisure；不是休闲，是处理事务。',
  implement: '词源：来自拉丁 implere，in 是 in，plere 是 fill；把计划填满成行动。',
  operate: '词源：来自拉丁 operari，opus 是 work；让机器或系统工作。',
  perform: '词源：来自古法语 parfournir，par 是 completely，fournir 是 provide；完整执行。',
  function: '词源：来自拉丁 fungi，意思是 perform/carry out；履行作用。',
  occur: '词源：来自拉丁 occurrere，ob 是 toward，currere 是 run；跑到面前、发生。',
  vary: '词源：来自拉丁 varius，意思是 diverse/different；变得不同。',
  range: '词源：来自古法语 rangier，意思是 arrange in a row；排成一列形成范围。',
  exceed: '词源：来自拉丁 excedere，ex 是 out，cedere 是 go；走出界限、超过。',
  restore: '词源：来自拉丁 restaurare，意思是 renew/rebuild；恢复原状。',
  preserve: '词源：来自拉丁 praeservare，prae 是 before，servare 是 keep；提前保护保存。',
  replace: '词源：re- again 加 place；把新东西放回原位置，替代旧东西。',
}
